title: Scott Shaffer # your name (or website title) here
logo: "/images/scott_circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data visualization 
  <br><br>
  Minneapolis, MN 
  <br><br>
  <a href="https://www.linkedin.com/in/scottdshaffer/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
